name: 'bincapz - binary capabilities change summary'
description: 'runs bincapz to summarize binary capabilities'
author: 'Natalie Somersall (@some-natalie)'
branding:
  icon: 'zoom-in'
  color: 'purple'

inputs:
  workdir:
    description: 'Working directory'
    required: false
    default: ${{ github.workspace }}
  format:
    description: 'Output format'
    required: true
    default: 'markdown'
  files:
    description: 'Files to analyze'
    required: false

runs:
  using: docker
  image: 'docker://ghcr.io/some-natalie/bincapz-action:latest'
