name: 'bincapz - binary capabilities change summary'
description: 'runs bincapz to summarize binary capabilities'
author: 'Natalie Somersall (@some-natalie)'
branding:
  icon: 'zoom-in'
  color: 'purple'

inputs:
  work-dir:
    description: 'Working directory'
    required: false
    default: ${{ github.workspace }}

runs:
  using: docker
  image: 'docker://ghcr.io/some-natalie/bincapz-action:latest'
