name: 'bincapz - binary capabilities change summary'
description: 'runs bincapz to summarize binary capabilities'
author: 'Natalie Somersall (@some-natalie)'
branding:
  icon: 'zoom-in'
  color: 'purple'

inputs:
  token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
  base:
    description: 'Base git revision'
    required: false
    default: ${{ github.base_ref }}
  head:
    description: 'Head git revision'
    required: false
    default: ${{ github.head_ref }}
  sha:
    description: 'SHA of the commit to check'
    required: false
    default: ${{ github.sha }}

runs:
  using: docker
  image: 'docker://ghcr.io/some-natalie/bincapz-action:latest'
